version: '3.8'
services:
  webapi:
    build:
        context: ./WebAPI
    ports:
      - "5000:8080"
    # depends_on:
    #   - sqlserver

  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: "Password123"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - ./Queries/Schema.sql:/Schema.sql
  #   command: >
  #     /bin/bash -c "
  #     /opt/mssql/bin/sqlservr & 
  #     sleep 20 && 
  #     /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123 -i /init.sql
  #     "
